# Generated by Django 4.0.5 on 2022-06-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('date', models.DateTimeField()),
                ('img', models.URLField()),
                ('price', models.IntegerField()),
                ('model', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('comment', models.CharField(max_length=400)),
                ('seller', models.CharField(max_length=100)),
            ],
        ),
    ]
