# Generated by Django 4.0.5 on 2022-06-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
