# Generated by Django 4.0.5 on 2022-06-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carad_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
